version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  web:
    build: .
    image: cryptocharts/cryptocharts:latest
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - web_data:/var/www/html
    restart: always
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"

  composer:
    image: kzap/composer:latest
    depends_on:
      - web
    volumes_from:
      - web
    working_dir: /var/www/html

  bower:
    image: kzap/bower:latest
    depends_on:
      - web
    volumes_from:
      - web
    working_dir: /var/www/html

volumes:
  db_data:
  web_data:
